### ISSUE TITLE
partial dumping in IW3,most important file not dumped

### ISSUE THREAD

**Issue by maxneed** [ZoneTool/zonetool#13]
zone tool iw3 not dumping completely the most important files like maps, source zone CSV file, vision file, mp folder, lights, images, fx......loaded sounds and sound are partially dumped in all version iw4, iw5, iw3 that makes the tool crash in buildzone ...running on windows 7...also iw3 in duming mode not showing message zone dumped kinda in a loop in a lot of different maps

**Comment by RektInator** [comment]
A few comments on your issue:

1. The dumped CSV is pure as reference. You shouldn't use these to rebuild fastfiles on different versions of the linker. This because it has a lot of redundant assets and might not result in what you would expect. If you want to port a model for example, simply add ``xmodel,model_name_here`` to your CSV file. This will include the model and ALL dependency assets.
2. Images are not dumped by zonetool, they can simply be extracted from the IWD files.
3. Map related assets are not dumped from IW3. If you want to port maps from IW3, you should use the IW4x tools instead.
4. FX is not yet supported as stated in the readme and issue #4
5. Loaded_sound and sounds are completely dumped, they are just in other fastfiles. Most fastfiles simply reference sound assets instead of really containing them. Reference asset names start with a ','. Most sounds are located in localized_common_mp.
6. The build zone command is not supposed to work on IW3. IW3 has its own linker for making fastfiles. Feel free to contribute however.

Map exporting for IW3 could be ported over from the IW4x source code but is not a priority.

**Comment by RektInator** [comment]
Regarding
> also iw3 in duming mode not showing message zone dumped kinda in a loop in a lot of different maps
This still needs to be implemented for IW3. A ZONETOOL_INFO line needs to be added to the DB_AddXAsset when the game loads a rawfile with the name of the fastfile. Every fastfile contains a rawfile with the name of the fastfile itself. This is the final asset in the fastfile. Feel free to port this code over to IW3 from IW4
