### ISSUE TITLE
[FEATURE]Support for V2 fastfiles version 277

### ISSUE THREAD

**Issue by ghostr92** [ZoneTool/zonetool#61]
Hello,
         Please add support for v2 fastfiles version 277.
Thanks

**Comment by RektInator** [comment]
There is no such thing as "v2 fastfiles". 277 is a "custom" format made by NTAuthority back around 2013/2014 for fourDeltaOne. It uses hacks to load the data from the file, probably because the file format was not completely understood back then.

And like mentioned before, this version of ZoneTool is not maintained anymore. If you want anything to change, you will have to do it yourself.

TLDR: no.
